### ISSUE TITLE
Is there a simple way to simulate time-shifting my load?

### ISSUE THREAD

**Issue by BillHoover** [hughescr/PGE-EV-Rate-Calculator#2]
First, this looks great. Thanks for the effort. In my case I just got an EV and want to figure out whether E-6 or EV-A is best, The problem is that the vast majority of my load is my pool pump, and I have that set to run in the off-peak E6 hours. Just looking at that usage under EV-A isn't appropriate for me, as I would also shift all of that load by 2 hours to keep it at the cheapest time.

Is there any way you can think of that I can (easily) simulate that? Thanks for any suggestions.
Bill

**Comment by hughescr** [comment]
In lib/data.js you could adjust the times that count as "peak", and basically shift those times by 2 hours for EV-A.  Starting at line 311 if you scroll to the end of the lines, you'll see the specified start/end hours for the different peak periods.  If you shift the peak times for EV, that would basically come out the same as shifting the load to a different time.

**Comment by BillHoover** [comment]
Thanks. I realized that after I thought about it. I haven't had a chance to
do that (and see what my results then look like). I should have added that
to the issue. I'll close it now. Thanks again for the tool. It will be more
meaningful when I simulate shifting my pool pump while computing the rest.
As far as the "EV" I only have a plug-in Prius, so the extra load I have is
only 3.31KWH, so the biggest changes for me are just the rate plan vs my
solar/pool pump.
